### ISSUE TITLE
signed integer is greater than maximum

### ISSUE THREAD

**Issue by hajsf** [mhalshehri/hijri-converter#11]
Trying to convert data in data frame, but got the amentioned error.

My code is:
```python
# import pandas
import pandas as pd
from hijri_converter import Hijri, Gregorian

#Click the 3 dots beside the file and copy the path
path = "/content/drive/MyDrive/ColabNotebooks/colabTraining/" 
# read csv data
data = pd.read_csv(path+'calender2022.csv')
h = Gregorian(1982, 12, 2).to_hijri()
# h2 = Gregorian(data['Date']).to_hijri()
print(h)

data['Date'] = pd.to_datetime(data['Date'], format='%Y-%m-%d %H:%M:%S') # format used in the file: '2022-01-01 0:00:00'
data['time'] = data['Date'].apply(lambda x: x.value)

data['hijri'] = data['Date'].apply(lambda x: Gregorian(x.value).to_hijri())

data
```

And the output is:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/98168280/181052573-5e4fb102-95f7-4b9b-9414-70076e6a6696.png">

**Comment by mhalshehri** [comment]
You are trying to instantiate the `Gregorian` object by passing the Pandas' Timestamp value while you should pass a date tuple (year, month, day). 

Your line should be like this:
```python
data['hijri'] = data['Date'].apply(lambda x: Gregorian(x.year, x.month, x.day).to_hijri())
```

Please refer to the [documentation](https://hijri-converter.readthedocs.io/en/stable/api.html#hijri_converter.convert.Gregorian).
