### ISSUE TITLE
from hijri_converter.convert import Gregorian, Hijri   ImportError: cannot import name 'Gregorian' from 'hijri_converter.convert'     [end of output]

### ISSUE THREAD

**Issue by ozgenezgi** [mhalshehri/hijri-converter#12]
I am getting this problem even though I deleted and installed the library.

**Comment by mhalshehri** [comment]
Please provide more context to understand your issue. e.g version, environment, code, stack trace, ...etc

**Comment by ozgenezgi** [comment]
First of all, I shared the problem directly, my apologies. My Python version is Python 3.9.0, the environment I'm running is jupyter notebook, actually I'm getting this error when trying to run the fbprophet library. I updated hijri converter to the latest version but it still returned this error

**Comment by mhalshehri** [comment]
This is likely an issue with a dependent library. However, please paste your code here and let me try to reproduce this issue.
