### ISSUE TITLE
500 Native SSL error

### ISSUE THREAD

**Issue by abimanyug26** [mhalshehri/hijri-converter#14]
Dear Team,

We are facing an issue with the below API link.
https://api.dralshehri.com/hijri-converter

### **Request we sent:** 
**JSON Payload:**
{
	"day": 15,
	"month": 3,
	"year": 2001,
	"calendar": "gregorian"
}

### **Response we received:**
**Code**: 500
**Response payload:**
**html title**: Application Server Error
**html body content**: 500 Native SSL error, Error is logged with Tag: {00348ca8}

Kindly let us know why we are receiving this kind of response/error in past few days.
Please feel free to reach out abimanyu.g@aspiredigital.com.

Best Regards,
Abimanyu G.

**Comment by mhalshehri** [comment]
Sorry to disappoint you. That API is not open to the public. If you need such a service, please reopen this issue and let me know how I can help.
