### ISSUE TITLE
not as ummulqura calender

### ISSUE THREAD

**Issue by NoraD1** [mhalshehri/hijri-converter#9]
Thank you for hijri-converter as it is very helpful. 
I would like to inform you that we found some inaccurate dates as shown below:

![image](https://user-images.githubusercontent.com/48954982/153713665-cc19a3a7-b946-4906-9de7-12b8cfcaee80.png)
Gregorian_Date: 1983-10-31
Hijri_converter: 1404-01-25

 while in (https://www.ummulqura.org.sa/Index.aspx) is : 
![image](https://user-images.githubusercontent.com/48954982/153713706-26405ad8-5ef2-4c5b-b179-2a957f0239a1.png)

ummulqura calender: 1404-01-24

sample of other dates that have the same issue:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/N762F~1.ALD/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/N762F~1.ALD/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

  |   |   |   |  
-- | -- | -- | -- | --
  | gregorian_date | hijri_converter | ummalqura_calender |  
  | 08/08/1989 | 1410-01-07 | 1410-01-06 |  
  | 22/12/1989 | 1410-05-24 | 1410-05-23 |  
  | 11/07/1990 | 1410-12-19 | 1410-12-18 |  
  | 26/09/1990 | 1411-03-07 | 1411-03-06 |  
  |   |   |   |  

</body>

</html>

Thanks in advance

**Comment by mhalshehri** [comment]
I appreciate your feedback 🙏🏼

Unfortunately, the official converter at [Ummulqura Calendar website] has some issues.

I know it is confusing, but check these calendars on the same website: [1404](https://www.ummulqura.org.sa/yearcalender.aspx?y=1404&l=True) [1410](https://www.ummulqura.org.sa/yearcalender.aspx?y=1410&l=True) [1411](https://www.ummulqura.org.sa/yearcalender.aspx?y=1411&l=True) and you will find the discrepancies.

The `hijri_converter` was carefully developed using the **tables** at Ummulqura Calendar website and verified using several other official sources such as Umm al-Qura newspaper and Umm al-Qura Comparative Calendar (issued by Saudi Ministry of Finance).

Perhaps we need to contact people behind [Ummulqura Calendar website] to fix their converter.

[Ummulqura Calendar website]: https://www.ummulqura.org.sa/Index.aspx
